dist: bionic
sudo: true

matrix:
  include:
    - name: CUDA 9
    env:
        -CUDA = 9.1.85
        -CUDA_SHORT = 9.1
        -UBUNTU_VERSION=ubuntu1804
    - os: linux
      compiler: gcc
      addons: &gcc7
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7', 'gcc-7']
      env:
        - CXX='g++-7'
        - CC='gcc-7'

before_install:
  - INSTALLER=cuda-repo-${UBUNTU_VERSION}_${CUDA}_amd64.deb
  - wget http://developer.download.nvidia.com/compute/cuda/repos/${UBUNTU_VERSION}/x86_64/${INSTALLER}
  - sudo dpkg -i ${INSTALLER}
  - wget https://developer.download.nvidia.com/compute/cuda/repos/${UBUNTU_VERSION}/x86_64/7fa2af80.pub
  - sudo apt-key add 7fa2af80.pub
  - sudo apt update -qq
  - sudo apt install -y cuda-core-${CUDA_SHORT/./-} cuda-cudart-dev-${CUDA_SHORT/./-} cuda-cufft-dev-${CUDA_SHORT/./-}
  - sudo apt clean
  - CUDA_HOME=/usr/local/cuda-${CUDA_SHORT}
  - LD_LIBRARY_PATH=${CUDA_HOME}/lib64:${LD_LIBRARY_PATH}
  - PATH=${CUDA_HOME}/bin:${PATH}
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test

install:
  - sudo git clone https://github.com/eigenteam/eigen-git-mirror.git /usr/local/include/eigen-git-mirror

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release i
  - make
