dist: bionic
sudo: true

matrix:
  include:
    - os: linux
      compiler: gcc
      addons: &gcc7
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7', 'gcc-7']
      env:
        - CXX='g++-7'
        - CC='gcc-7'

before_install:
  - sudo add-apt-repository -y ppa:graphics-drivers/ppa
  - sudo apt update
  - sudo apt-get install ubuntu-drivers-common
  #- sudo ubuntu-drivers auto-install
  - sudo reboot now
  - sudo apt install nvidia-cuda-toolkit gcc-6
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test

install:
  - sudo git clone https://github.com/eigenteam/eigen-git-mirror.git /usr/local/include/eigen-git-mirror

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release i
  - make
